services:
  - type: web
    name: mami-supermarket-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: chmod +x start.sh && ./start.sh
    plan: free 
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mami-supermarket-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.10.0
    healthCheckPath: /health
    autoDeploy: true
    buildFilter:
      paths: ["mami-supermarket-backend/**"]
    repo: https://github.com/matanmalka1/mami-supermarket-backend.git

  - type: web 
    name: mami-supermarket-frontend
    env: static 
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: mami-supermarket-backend
          property: host
    buildFilter:
      paths: ["mami-supermarket-frontend/**"]
    repo: https://github.com/matanmalka1/mami-supermarket-frontend.git

databases:
  - name: mami-supermarket-db
    plan: free